# techlanches-sql-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: techlanches-sql
  namespace: techlanches
spec:
  serviceName: "techlanches-sql"
  replicas: 1
  selector:
    matchLabels:
      app: techlanches-sql
  template:
    metadata:
      labels:
        app: techlanches-sql
    spec:
      containers:
      - name: sql-server
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: techlanches-secrets
              key: SA_PASSWORD
        - name: ACCEPT_EULA
          value: "Y"
  volumeClaimTemplates:
  - metadata:
      name: mssql-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
