version: '3.9'

services:
  webapi:
    build:
        context: ./src/TechLanches/
        dockerfile: Dockerfile
    container_name: api-dotnet6
    ports:
      - "5050:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=techlanches;User=sa;Password=Qwert@12345
    networks:
      - techlanches-network
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Qwert@12345
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - techlanches-network

networks:
  techlanches-network:

volumes:
  sqlserverdata: