# techlanches-api-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: techlanches-api-service
  namespace: techlanches
spec:
  selector:
    app: techlanches-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5050
  type: LoadBalancer