# techlanches-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: techlanches-secrets
  namespace: techlanches
type: Opaque
data:
  #DefaultConnection: U2VydmVyPXRlY2hsYW5jaGVzLXNxbC0wLDE0MzM7RGF0YWJhc2U9dGVjaGxhbmNoZXM7VXNlcj1zYTtQYXNzd29yZD1Rd2VydEAxMjM0NQ==
  #DefaultConnection: U2VydmVyPTEyNy4wLjAuMSwxNDMzO0RhdGFiYXNlPXRlY2hsYW5jaGVzO1VzZXI9c2E7UGFzc3dvcmQ9UXdlcnRAMTIzNDU=
  #DefaultConnection: U2VydmVyPXRlY2hsYW5jaGVzLXNxbC1zZXJ2aWNlO0RhdGFiYXNlPXRlY2hsYW5jaGVzO1VzZXI9c2E7UGFzc3dvcmQ9UXdlcnRAMTIzNDU=
  #DefaultConnection: U2VydmVyPXRlY2hsYW5jaGVzLXNxbC1zZXJ2aWNlLDE0MzM7RGF0YWJhc2U9dGVjaGxhbmNoZXM7VXNlcj1zYTtQYXNzd29yZD1Rd2VydEAxMjM0NQ==
  #DefaultConnection: RGF0YSBTb3VyY2U9dGVjaGxhbmNoZXMtc3FsLXNlcnZpY2UsMzI2NTA7SW5pdGlhbCBDYXRhbG9nPXRlY2hsYW5jaGVzO1VzZXIgSWQ9c2E7UGFzc3dvcmQ9UXdlcnRAMTIzNDU7
  DefaultConnection: U2VydmVyPXRlY2hsYW5jaGVzLXNxbC1zZXJ2aWNlO0luaXRpYWwgQ2F0YWxvZz10ZWNobGFuY2hlcztVc2VyIElkPXNhO1Bhc3N3b3JkPVF3ZXJ0QDEyMzQ1Ow==
  SA_PASSWORD: UXdlcnR5QDEyMzQ1 # Qwerty@12345