# techlanches-sql-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: techlanches-sql-pv
  namespace: techlanches
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/path/to/sql/data"