apiVersion: v1
kind: Pod
metadata:
  namespace: techlanches
  name: ubuntu-pod
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu-container
    image: ubuntu:latest
    command: [ "/bin/sleep", "infinity" ]
