# techlanches-worker-hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: techlanches-worker-hpa
  namespace: techlanches
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: techlanches-worker
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70 
  behavior:
   scaleDown:
    stabilizationWindowSeconds: 30