apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok
  namespace: techlanches
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngrok
  template:
    metadata:
      labels:
        app: ngrok
    spec:
      containers:
        - name: ngrok
          image: wernight/ngrok
          ports:
            - containerPort: 4040 
          #command: ["ngrok", "http", "techlanches-api-service:5050"]
          command: 
            - "sh"
            - "-c"
            - >
              /bin/ngrok authtoken 2ZUXQw51GKTrQqI9HCc3lMvzI3v_JtCKn4NG2mgvYdNSWLXc &&
              /bin/ngrok http --region=us --log=stdout --hostname=spider-tight-previously.ngrok-free.app techlanches-api-service:5050
---
apiVersion: v1
kind: Service
metadata:
  name: ngrok
  namespace: techlanches
spec:
  ports:
    - name: ngrok-http
      protocol: TCP
      port: 4040 
      targetPort: 4040
  selector:
    app: ngrok
  type: LoadBalancer
