# techlanches-api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: techlanches-api
  namespace: techlanches
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techlanches-api
  template:
    metadata:
      labels:
        app: techlanches-api
    spec:
      containers:
        - name: techlanches-api
          image: g124soat/techlanches-api:1.0.1
          ports:
            - containerPort: 5050
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: techlanches-secrets
                  key: DefaultConnection

---
apiVersion: v1
kind: Service
metadata:
  name: techlanches-api-service
  namespace: techlanches
spec:
  selector:
    app: techlanches-api
  ports:
    - protocol: TCP
      port: 31111
      targetPort: 5050
  type: LoadBalancer