# techlanches-api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: techlanches-api
  namespace: techlanches
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techlanches-api
  template:
    metadata:
      labels:
        app: techlanches-api
    spec:
      containers:
        - name: techlanches-api
          image: g124soat/techlanches-api:develop # usar latest quando for pra main
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            # limits: 
            #   cpu: "1"
            #   memory: "1Gi" Removi para testar o HPA... Validar se deve ser usado no futuro.
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: techlanches-secrets
                  key: DefaultConnection

---
apiVersion: v1
kind: Service
metadata:
  name: techlanches-api-service
  namespace: techlanches
spec:
  selector:
    app: techlanches-api
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 80
  type: LoadBalancer