# techlanches-api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: techlanches-api
  namespace: techlanches
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techlanches-api
  template:
    metadata:
      labels:
        app: techlanches-api
    spec:
      containers:
        - name: techlanches-api
          image: g124soat/techlanches-api:latest
          ports:
            - containerPort: 5050