apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: techlanches
spec:
  ports:
  - port: 5672
    name: amqp
  - port: 15672
    name: http
  selector:
    app: rabbitmq
  type: LoadBalancer

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: techlanches
spec:
  serviceName: "rabbitmq"
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      hostname: techlanches
      containers:
      - name: rabbitmq
        image: rabbitmq:management
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env:
          - name: RABBITMQ_DEFAULT_USER
            valueFrom:
              secretKeyRef:
                name: techlanches-secrets
                key: RABBITMQ_DEFAULT_USER
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: techlanches-secrets
                key: RABBITMQ_DEFAULT_PASS
        volumeMounts:
        - name: rabbit-data
          mountPath: /var/lib/rabbitmq/mnesia

      volumes:
      - name: rabbit-data
        persistentVolumeClaim:
          claimName: rabbit-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbit-data
  namespace: techlanches
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi