# techlanches-worker-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: techlanches-worker
  namespace: techlanches
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techlanches-worker
  template:
    metadata:
      labels:
        app: techlanches-worker
    spec:
      containers:
        - name: techlanches-worker
          image: g124soat/techlanches-worker:develop # usar latest quando for pra main
          ports:
            - containerPort: 5060
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: techlanches-secrets
                  key: DefaultConnection

---
apiVersion: v1
kind: Service
metadata:
  name: techlanches-worker-service
  namespace: techlanches
spec:
  selector:
    app: techlanches-worker
  ports:
    - protocol: TCP
      port: 5060
      targetPort: 5060
  type: LoadBalancer