apiVersion: v1
kind: Service
metadata:
  name: techlanches-sql-service
  namespace: techlanches
spec:
  ports:
  - name: techlanches-sql
    port: 1433
    targetPort: 1433
  selector:
    name: techlanches-sql
  type: LoadBalancer