name: API Docker Publish Develop

on:
  push:
    branches:
      - develop
  workflow_run:
    workflows: ["Build API Docker Image"]
    types:
      - completed
  workflow_dispatch:

jobs:
  publish-to-docker-hub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
      - name: Build and Push Docker image
        run: |
          cd src/TechLanches
          TAG=$(date +%Y%m%d%H%M%S)
          docker build -f Dockerfile.API -t ${{secrets.DOCKER_USERNAME}}/techlanches-api:$TAG -t ${{secrets.DOCKER_USERNAME}}/techlanches-api:develop . --no-cache
          docker push ${{secrets.DOCKER_USERNAME}}/techlanches-api:$TAG
          docker push ${{secrets.DOCKER_USERNAME}}/techlanches-api:develop
          
        #  docker build -f Dockerfile.API -t ${{secrets.DOCKER_USERNAME}}/techlanches-api:1.0.7 . --no-cache         
        # docker build -f Dockerfile.API -t ${{secrets.DOCKER_USERNAME}}/techlanches-api:develop . --no-cache
        
      #- name: Docker 
        #run: docker push ${{secrets.DOCKER_USERNAME}}/techlanches-api:develop
        #run: docker push ${{secrets.DOCKER_USERNAME}}/techlanches-api:1.0.7
