name: Build Worker Docker Image

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      run: |
        cd src/TechLanches
        docker build -f Dockerfile.Worker -t techlanches-worker-image:latest . --no-cache

    - name: Clean up
      run: docker system prune -af
